export const quickReactionsTexts = [
  "Wow, that’s awesome!",
  "Look at you go!",
  "I see you!",
  "That’s something to be proud of.",
  "You did it!",
  "One step at a time. And you took one.",
  "That counts. Always.",
  "Hey, that’s real progress.",
  "Yes! You showed up.",
  "You really did a thing, huh?",
  "Small wins are big wins.",
  "That matters.",
  "You’re making it happen.",
  "Go you!",
  "That took something.",
  "You moved forward. That’s enough.",
  "That’s a moment. Keep it.",
  "You’re not stuck — look at you!",
  "I’m proud of you already.",
  "That took effort. I noticed.",
  "Good on you.",
  "Another brick in the road.",
  "You’re building momentum.",
  "Yes, yes, yes!",
  "You did your part.",
  "It’s happening.",
  "You did one thing. And that’s real.",
  "That’s how it starts.",
  "You chose to act.",
  "Another win for the day.",
  "I love that for you.",
  "You got it done.",
  "You’re not invisible. I see this.",
  "Even small things echo.",
  "You moved. That’s courage.",
  "There it is. Proof you tried.",
  "You gave it a go. I respect that.",
  "Nice. Very nice.",
  "This matters.",
  "You did something. That’s enough.",
  "We love that.",
  "Oh heck yeah.",
  "You legend.",
  "Yep. That’s the stuff.",
  "Something moved. It was you.",
  "Big energy from a little action.",
  "Don’t downplay that.",
  "You did it, and I noticed.",
  "That’s a ripple.",
  "That’s how change begins.",
];

export const getRandomFromArray = (array: string[]) => {
  return array[Math.floor(Math.random() * array.length)];
};

export const getRandomQuickReactionText = () => {
  return getRandomFromArray(quickReactionsTexts);
};
